// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:56fc7635-6ff3-4a73-af5b-ca90875af253",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_wh3Nhc9sm",
    "aws_user_pools_web_client_id": "7v4cgb7abce23cniihlsdd30k1",
    // "oauth": {
    //     "domain": "memorymaestro8db078ca-8db078ca-mmapi.auth.us-east-1.amazoncognito.com",
    //     "scope": [
    //         "phone",
    //         "email",
    //         "openid",
    //         "profile",
    //         "aws.cognito.signin.user.admin"
    //     ],
    //     "redirectSignIn": "http://localhost:3000",
    //     "redirectSignOut": "http://localhost:3000",
    //     "responseType": "code"
    // },
    // "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
